### ISSUE TITLE
drag scroll not working in mobile view

### ISSUE THREAD

**Issue by suresh2018** [bfwg/angular2-drag-scroll#26] opened 2017-08-22 09:40 UTC

**Comment by bfwg** [comment] 2017-08-22 23:38
Relates to #20

**Comment by bfwg** [comment] 2017-08-23 00:52
The PR is up, I'm just going to review the code again and push a new version. Feel free to throw in any comments if you think there is something wrong in the PR code. @suresh2018 @nachocoig.

**Comment by bfwg** [comment] 2017-08-24 01:57
1.3.7 is out.

**Comment by suresh2018** [comment] 2017-08-24 07:42
@bfwg 

1.3.6 showed click cancel error but 1.3.7 not showing this error .
this version also  drag scroll not working .

**Comment by suresh2018** [comment] 2017-08-24 07:47
![image](https://user-images.githubusercontent.com/30258184/29655367-8232450c-88ce-11e7-853f-203292f85300.png)

**Comment by bfwg** [comment] 2017-08-24 16:53
@suresh2018 It is working for me. Is drag scroll working for you on desktop view?

**Comment by suresh2018** [comment] 2017-08-25 06:07
desktop working fine .but not moblie

**Comment by bfwg** [comment] 2017-08-25 06:09
Weird, can you show me a chunk of your carousel code? Have you tried on an actual device?

**Comment by suresh2018** [comment] 2017-08-25 06:32
<div class="hideoverflow" drag-scroll  >
                <img *ngFor="let img of pic.images; let idx = index" [src]="img .Image" 
                  class="scroll-images">
              </div>

**Comment by suresh2018** [comment] 2017-08-25 06:35
div class="hideoverflow" drag-scroll  

                img *ngFor="let img of pic.images; let idx = index" [src]="img .Image" 
                  class="scroll-images"

              div

**Comment by rahil051** [comment] 2017-08-25 06:36
Have you people tried the drag-scroll demo (in README.md) on touch devices ?

**Comment by suresh2018** [comment] 2017-08-25 06:43
i will check let you know

**Comment by suresh2018** [comment] 2017-08-25 06:47
@rahil

demo not work touch device

**Comment by rahil051** [comment] 2017-08-25 11:35
@suresh2018 @bfwg I am using this lib in my Ionic 2 project. The scroll works fine for me, if I emulate on Chrome Dev Tools Mobile emulator, but there are few major problems I am having
1. The screen where drag-scroll is used, disables all click events on that screen
For example
```html
<ion-content>
  <ion-grid>
    <ion-row>
      <ion-col>
        <button ion-button (click)="foo()">Click Me!</button>
        <!-- On mobile view click stops working. If I remove [drag-scroll] it starts working again -->
      </ion-col>
      <ion-col>
        <div drag-scroll>
          <!-- *ngFor let item of items (horizontal scroll) -->
          <button ion-button (click)="someFunc()"></button>
          <!-- also click event don't work in mobile view. Fixes if [drag-scroll] is removed! -->
        </div>
      </ion-col>
      <ion-col>
        <button ion-button (click)="bar()">Click Me Again!</button>
        <!-- On mobile view click stops working. If I remove [drag-scroll] it starts working again -->
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```
2. [scrollbar-hidden]="true" removes the entire drag-scroll component from the screen (Ionic 2). "false" doesn't.

**Comment by bfwg** [comment] 2017-08-25 17:34
Hi, @rahil051 
1. click event not firing is fixed in v1.3.7.
2. you need to either write `scrollbar-hidden="true"` or simply `scrollbar-hidden` for a fixed attribute. If you want to bind the attribute to a variable in your component, you need to write `[scrollbar-hidden]="flagVariable"` note when to use the square brackets.

For more information, please checkout https://github.com/bfwg/angular2-drag-scroll/blob/master/demo/app/home/home.component.html#L26

**Comment by bfwg** [comment] 2017-08-25 17:37
@suresh2018 I failed to reproduce the touch issue on iPhone 6 Plus. I'm testing on the demo app. Can you clone this repository and do a `npm install && npm start` to startup the demo app on port `:4200`? You can use the Chrome devtool to check if it is working for you.

**Comment by nachocoig** [comment] 2017-08-28 11:13
Hello @bfwg, sorry for my late reply (I was in minivacations ;D)

I reinstalled your angular component demo and yes, it works in mobile version!
I have also tried using it into my app, and it works too!

Thanks for ur attention! 

**Nice work!**

**Comment by suresh2018** [comment] 2017-08-28 11:58
@nachocoig you checked in touch mobile devices?

**Comment by suresh2018** [comment] 2017-08-28 12:12
Hi @bfwg,

finally , i find this issue .
need to set horizontal width then only it wil works

thanks ..

**Comment by suresh2018** [comment] 2017-08-28 12:13
Hi @bfwg,
finally , i find this issue .
need to set horizontal width then only it wil works
thanks

**Comment by bfwg** [comment] 2017-08-28 17:53
Sweet, glad that worked for you guys. I can safely close this issue now.

Thanks for reporting this issue again!

**Closed by bfwg** 2017-08-28 17:53 UTC
Labels: bug

**Comment by kzntswsk** [comment] 2020-06-16 01:32
Hey, this is by far the best ng2 carousel library! I can't seem to get it to work on mobile, though. 

- Demo app works fine on desktop and mobile
- My code only works on desktop. Drag doesn't work on mobile

>  need to set horizontal width then only it wil works

I've set width:100% on drag-scroll, on a wrapper outside of drag-scroll and on a div inside drag-scroll (all possible combinations) and it's still not working.

Is there any additional library I should add to my project for it to work on mobile too? What am I missing exactly? I'm at a loss.

**Comment by bfwg** [comment] 2020-06-16 08:05
Hey @kzntswsk , thanks for the feedback. Can you make a small demo with https://plnkr.co/? I can't help you without toying your code 😄

**Comment by ErraticFox** [comment] 2020-10-03 12:31
> Hey @kzntswsk , thanks for the feedback. Can you make a small demo with https://plnkr.co/? I can't help you without toying your code 😄

I've also encountered this. I can't do a plnkr right now but it seems to only do this with `scrollbar-hidden="true"` whereas just the `scrollbar-hidden` doesn't do anything.

**Comment by omararturo** [comment] 2020-10-12 19:42
The problem is that events are not fired in Chrome Dev Tools in device mode

**Comment by lh7dev** [comment] 2021-12-03 23:32
> > Hey @kzntswsk , thanks for the feedback. Can you make a small demo with https://plnkr.co/? I can't help you without toying your code 😄
> 
> I've also encountered this. I can't do a plnkr right now but it seems to only do this with `scrollbar-hidden="true"` whereas just the `scrollbar-hidden` doesn't do anything.
> 
> EDIT: If I go to `.drag-scroll-content` in dev tools and unselect `overflow: hidden auto;` it fixes it, but the scrollbar is again visible. So this would seem to have to do with the method used to hide the scrollbar for mobile.

Just as @ErraticFox said... whenever I use `scrollbar-hidden="true"` my component stop reacting to gestures.
Angular syntax doesn't allow using just `scrollbar-hidden` without setting a value.

my walkaround was to hide the scrollbar using CSS

```
  drag-scroll {
  width: 100%;
  max-width: 100vw;
  height: 350px;
  display: flex;
  z-index: 18;
  .item-text {
    p {
      white-space: normal !important;
    }
  }

  ::ng-deep *::-webkit-scrollbar {
    display: none !important;
  }
  ::ng-deep * {
    -ms-overflow-style: none !important; /* IE and Edge */
    scrollbar-width: none !important; /* Firefox */
  }
}
```

I am currently using `Angular 12` and `ngx-drag-scroll@12.0.0-beta.2`

I hope this helps

**Comment by davrob01** [comment] 2022-07-06 23:13
I can confirm I also experience drag/touch scroll not working on mobile devices when [scrollbar-hidden]="true" is used. I'm using angular 13 and ngx-drag-scroll 13.0.2.

However, I just wanted to chime in with another workaround that some people may prefer. Basically it's the opposite of what @lh7dev is doing. I keep the [scrollbar-hidden]="true" but then add the following CSS rule, which re-enables a browser scroll bar but only when a touch device is being used (at least that is what the CSS media query is supposed to do). It seems to work well. And on most mobile browsers the scroll bar, by default, is either really small or not shown at all, so nothing more needs to be done to hide it.

```
@media (hover: none) and (pointer: coarse) {
  ::ng-deep .drag-scroll-content {
    overflow: auto !important;
  }
}
```
